name: Docker Publish
on:
  push:
    branches: [ master ]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         push: true
         tags: ghcr.io/huggablesquare/vsco-map:latest
